version: '3'

volumes:
  node_modules:

services:
  site:
    build: _docker
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
      - node_modules:/srv/jekyll/node_modules
    ports:
      - 4000:4000
      - 35729:35729
      - 3000:3000